workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Clean build
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build Android APK

        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk

      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - flutter_drive.log

  web-workflow:
    name: Web Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      scripts:
        - name: Publish to Codemagic Static Pages
          script: |
            echo "Publishing to Codemagic Static Pages..."
            # Publishing is handled automatically by Codemagic when configured in the UI or via API, 
            # but for static pages we often just need the artifact. 
            # If using Codemagic Static Pages, we simply ensure the 'build/web' artifact is uploaded.
